let dataa=[
    {
        "id":1,
        "brand":"I-PHONE",
        "category":"mobile",
        "brandimage":"https://i.pinimg.com/originals/53/9f/f3/539ff32ec9d53f12952896dbbf6a28cb.png",
        "image":"https://img.jabko.ua/image/cache/catalog/111/iph-15-pr0full.jpg",
        "name":"I-PHONE 15 PRO MAX",
        "storage":"256 GB ROM",
        "display":"17.02 cm (6.7 inch) Super Retina XDR Display",
        "camera":"48MP + 12MP + 12MP | 12MP Front Camera",
        "processor":"A17 Pro Chip, 6 Core Processor Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Super Retina XDR Display",
        "displaytype":"All Screen OLED Display",
        "price":154000

    },
    {
        "id":2,
        "category":"mobile",
        "brand":"SAMSUNG",
        "brandimage":"https://logos-world.net/wp-content/uploads/2020/11/Samsung-Galaxy-Logo-2015-present.png",
        "image":"https://image-us.samsung.com/us/smartphones/galaxy-s23-ultra/images/gallery/lavender/01-DM3-Lavender-PDP-1600x1200.jpg",
        "name":"SAMSUNG S23 ULTRA",
        "storage":"12 GB RAM | 256 GB ROM",
        "display":"17.27 cm (6.8 inch) Quad HD+ Display",
        "camera":"48MP + 12MP + 12MP | 12MP Front Camera",
        "processor":"Qualcomm Snapdragon 8 Gen 2 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Quad HD+",
        "displaytype":"Full HD+ Dynamic AMOLED 2X",
        "price":124999
    },
    {
        "id":3,
        "category":"mobile",
        "brand":"OPPO",
        "brandimage":"https://1000logos.net/wp-content/uploads/2018/10/Oppo-logo.jpg",
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/m/e/3/-original-imah37gwn2xbvzhy.jpeg?q=70",
        "name":"OPPO K12",
        "storage":"6 GB RAM | 128 GB ROM | Expandable Upto 1 TB",
        "display":"16.94 cm (6.67 inch) HD Display",
        "camera":"32MP + 2MP | 8MP Front Camera",
        "processor":"Dimensity 6300 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"HD",
        "displaytype":"LCD",
        "price":12999
    },
    {
        "id":4,
        "category":"mobile",
        "brand":"VIVO",
        "brandimage":"https://1000logos.net/wp-content/uploads/2022/02/Vivo-Logo.jpg",
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/y/4/r/-original-imah3hvkfgeg3zky.jpeg?q=70",
        "name":"vivo V40 5G",
        "storage":"12 GB RAM | 512 GB ROM",
        "display":"17.22 cm (6.78 inch) Full HD+ Display",
        "camera":"50MP + 50MP | 50MP Front Camera",
        "processor":"Snapdragon 7 Gen 3 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Full HD+",
        "displaytype":"Full HD+ AMOLED",
        "price":41999
    },
    {
        "id":5,
        "category":"mobile",
        "brand":"ONEPLUS",
        "brandimage":"https://logowik.com/content/uploads/images/oneplus-new8781.jpg",
        "image":"https://techring.in/wp-content/uploads/2023/01/OnePlus-12R.jpg",
        "name":"OnePlus 12R",
        "storage":"16 GB RAM | 256 GB ROM",
        "display":"17.22 cm (6.78 inch) Display",
        "camera":"50MP Rear Camera",
        "processor":"Qualcomm Snapdragon 8 Gen 2 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Super Retina XDR Display",
        "displaytype":"All Screen OLED Display",
        "price":43699
    },
    {
        "id":6,
        "category":"mobile",
        "brand":"NOTHING PHONE",
        "brandimage":"https://cdn.neowin.com/news/images/uploaded/2021/01/1611746613_nothing_white_story.jpg",
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/i/s/b/-original-imagrdefh2xgenzz.jpeg?q=70",
        "name":"Nothing Phone (2)",
        "storage":"12 GB RAM | 256 GB ROM",
        "display":"17.02 cm (6.7 inch) Full HD+ Display",
        "camera":"50 MP(OIS) +50MP | 32MP Front Camera",
        "processor":"Qualcomm Snapdragon 8+ Gen 1 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Full HD+",
        "displaytype":"Flexible LTPO AMOLED Display",
        "price":49999
    },
    {
        "id":7,
        "brand":"REDMI",
        "category":"mobile",
        "brandimage":"https://wallpapercave.com/wp/wp6707768.png",
        "image":"https://rukminim2.flixcart.com/image/312/312/xif0q/mobile/0/g/w/note-12-5g-mzb0eiain-redmi-original-imagpgr9ngapjhxq.jpeg?q=70",
        "name":"REDMI Note 12 5G",
        "storage":"8 GB RAM | 256 GB ROM | Expandable Upto 1 TB",
        "display":"16.94 cm (6.67 inch) Full HD+ AMOLED Display",
        "camera":"48MP + 8MP + 2MP | 13MP Front Camera",
        "processor":"Qualcomm Snapdragon 4 Gen 1 Processor",
        "warranty":"1 YEAR WARRANTY",
        "resolutiontype":"Full HD+ AMOLED Display",
        "displaytype":"Full HD+ 120 Hz Super AMOLED Display",
        "price":15998
    }
   
]
export default dataa